### Pytorch Tutorial
#### Tensors Basics
A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array.It is a term and set of techniques known in machine learning in the training and operation of deep learning models can be described in terms of tensors.
In many cases tensors are used as a replacement for NumPy to use the power of GPUs.

Tensors are a type of data structure used in linear algebra, and like vectors and matrices, you can calculate arithmetic operations with tensors.


#### Detailed Explanation of Tensors
Tensors are a fundamental aspect of PyTorch and are used to represent data in deep learning models. They are similar to NumPy arrays but come with additional capabilities like GPU acceleration.

#### Examples of Tensor Creation
- `torch.Tensor([1, 2, 3])`: Creates a tensor with specified values.
- `torch.zeros(2, 3)`: Creates a 2x3 tensor filled with zeros.
- `torch.ones(3, 2)`: Creates a 3x2 tensor filled with ones.
- `torch.eye(3)`: Creates a 3x3 identity matrix.

These examples demonstrate various ways to create tensors in PyTorch.


In [1]:
import torch

In [2]:
torch.__version__

'2.1.1+cpu'

In [3]:
import numpy as np

In [4]:
lst=[3,4,5,6]
arr=np.array(lst)

In [5]:
arr

array([3, 4, 5, 6])

In [6]:
arr.dtype

dtype('int32')

### Convert Numpy To Pytorch Tensors


#### In-Depth Conversion Techniques
Converting between NumPy arrays and PyTorch tensors is seamless, which allows for easy integration with other Python libraries.

##### Conversion Examples
- From NumPy to PyTorch: `torch_tensor = torch.from_numpy(numpy_array)`.
- From PyTorch to NumPy: `numpy_array = torch_tensor.numpy()`.

This interoperability is vital for data preprocessing and postprocessing in machine learning workflows.


In [7]:
tensors=torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6], dtype=torch.int32)

In [8]:
### Indexing similar to numpy
tensors[2]


tensor(5, dtype=torch.int32)

In [9]:
tensors[1:4]

tensor([4, 5, 6], dtype=torch.int32)

In [10]:
#### Disadvantage of from_numpy. The array and tensor uses the same memory location
tensors[3]=100

In [11]:
tensors

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [12]:
arr

array([  3,   4,   5, 100])

In [13]:
### Prevent this by using torch.tensor
tensor_arr=torch.tensor(arr)
tensor_arr

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [14]:
tensor_arr[3]=120
print(tensor_arr)
print(arr)

tensor([  3,   4,   5, 120], dtype=torch.int32)
[  3   4   5 100]


In [15]:
##zeros and ones
torch.zeros(2,3,dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [16]:
torch.ones(2,3,dtype=torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [17]:
a=torch.tensor(np.arange(0,15).reshape(5,3))

In [18]:
a[:,0:2]

tensor([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10],
        [12, 13]], dtype=torch.int32)

##### Arithmetic Operation

In [19]:
a = torch.tensor([3,4,5], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a + b)

tensor([ 7.,  9., 11.])


In [20]:
torch.add(a,b)

tensor([ 7.,  9., 11.])

In [21]:
c=torch.zeros(3)

In [22]:
torch.add(a,b,out=c)

tensor([ 7.,  9., 11.])

In [23]:
c

tensor([ 7.,  9., 11.])

In [24]:
##### Some more operations
a = torch.tensor([3,4,5], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)

In [25]:
### tensor[7,9,15]
torch.add(a,b).sum()

tensor(27.)

##### Dot Products and Mult Operations

In [26]:
x= torch.tensor([3,4,5], dtype=torch.float)
y = torch.tensor([4,5,6], dtype=torch.float)

In [27]:
x.mul(y)

tensor([12., 20., 30.])

In [28]:
x.dot(y)

tensor(62.)

# Matrix Multiplication

In [29]:
x = torch.tensor([[1,4,2],[1,5,5]], dtype=torch.float)
y = torch.tensor([[5,7],[8,6],[9,11]], dtype=torch.float)

In [30]:
torch.matmul(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [31]:
torch.mm(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [32]:
x@y

tensor([[55., 53.],
        [90., 92.]])


### Expanded Introduction to Tensors in PyTorch
Tensors are the fundamental building blocks in PyTorch. They are similar to NumPy arrays but have additional capabilities, such as GPU support, which makes them suitable for deep learning. Tensors can store data of various dimensions, making them versatile for different types of data structures like scalars (0D), vectors (1D), matrices (2D), and higher-dimensional data.



### Basic Tensor Operations
Let's explore some basic tensor operations which are essential for deep learning tasks.


In [33]:

# Creating tensors
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([4, 5, 6])

# Basic operations
sum_ab = tensor_a + tensor_b
product_ab = tensor_a * tensor_b



### Tensor and NumPy Interoperability
PyTorch tensors can be easily converted to and from NumPy arrays. This interoperability is important for integrating PyTorch with other scientific computing libraries that use NumPy.


In [34]:

# Converting a NumPy array to a PyTorch Tensor
np_array = np.array([7, 8, 9])
tensor_from_np = torch.from_numpy(np_array)

# Converting a PyTorch Tensor to a NumPy array
tensor_to_np = tensor_from_np.numpy()



### GPU Utilization in PyTorch
PyTorch can utilize GPUs to accelerate its numerical computations. For deep learning models, this can lead to significantly faster training times.



#### Detailed GPU Utilization
Using GPUs can significantly speed up computations. PyTorch makes it easy to transfer tensors to and from a GPU.

##### GPU Acceleration Example
- Check if GPU is available: `torch.cuda.is_available()`.
- Move tensor to GPU: `tensor = tensor.to('cuda')`.

This section can include benchmarks to illustrate the performance improvements when using GPUs.


In [35]:

# Checking if GPU is available and moving tensors to GPU
if torch.cuda.is_available():
    tensor_a = tensor_a.to('cuda')
    tensor_b = tensor_b.to('cuda')

print(tensor_a.device)
print(tensor_b.device)

    

cpu
cpu



### Automatic Differentiation with Autograd
PyTorch's autograd system enables automatic computation of gradients, which is essential for backpropagation in neural networks.



#### Exploring Autograd
Autograd in PyTorch automates the computation of backward passes in neural networks. It computes gradients automatically, which are essential for the optimization process in learning.

##### Autograd Example
- Create a tensor for differentiation: `x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)`.
- Define a function: `y = x ** 2`.
- Compute gradients: `y.backward()`.

This example shows how gradients are computed, which is crucial for training deep learning models.


In [36]:

# Creating tensors for autograd
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
y = x ** 2

# Computing gradients
y.backward(torch.tensor([1.0, 1.0, 1.0]))
x.grad  # Derivatives of y with respect to x


tensor([2., 4., 6.])


### More on Basic Tensor Operations
In addition to the basic tensor operations already shown, PyTorch provides a variety of functions to manipulate tensors. These include:

1. **Reshaping**: Changing the shape of a tensor without changing its data.
2. **Indexing and Slicing**: Accessing parts of tensors using indices.
3. **Tensor Concatenation**: Combining multiple tensors into one.
4. **Broadcasting**: Automatically expanding tensor sizes for compatible operations.


In [37]:

# Examples of Basic Tensor Operations

# Reshaping tensors
tensor_reshaped = tensor_a.view(-1, 1)  # Reshaping tensor_a to a column vector

# Indexing and slicing
first_element = tensor_a[0]  # Accessing the first element
tensor_slice = tensor_a[1:3]  # Slicing tensor_a from index 1 to 2

# Tensor concatenation
concatenated_tensor = torch.cat((tensor_a, tensor_b), dim=0)  # Concatenating along the first dimension

# Broadcasting example
broadcasted_sum = tensor_a + torch.tensor([1])  # Adding 1 to each element of tensor_a



### Advanced Tensor Operations
More advanced tensor operations are crucial for complex tasks in PyTorch. These include:

1. **Matrix Multiplication**: Essential operation in neural networks.
2. **Element-wise Operations**: Operations performed element-wise on tensors.
3. **In-place Operations**: Operations that modify tensors in-place to save memory.


In [38]:

# Examples of Advanced Tensor Operations

# Matrix multiplication
matrix_a = torch.tensor([[1, 2], [3, 4]])
matrix_b = torch.tensor([[5, 6], [7, 8]])
product_matrix = torch.matmul(matrix_a, matrix_b)  # Matrix multiplication

# Element-wise multiplication
elementwise_product = matrix_a * matrix_b

# In-place operations
tensor_a.add_(5)  # Adds 5 to each element of tensor_a in-place


tensor([6, 7, 8])